service: lambda-extraction

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:*"
        - "s3:*"
      Resource:
        - "*"

functions:
  extract:
    name: lambda-extraction
    memorySize: 512
    timeout: 300
    handler: src/functions/extract/extract.handler
    environment: 
      BATCH_SIZE: 500
  transform:
    name: lambda-transform
    memorySize: 512
    timeout: 300
    handler: src/functions/transform/index.transform    

stepFunctions:
  stateMachines:
    processfile:
      name: stepf-process-delete
      definition:
        Comment: "A sample application"
        StartAt: Extract
        States:
          Extract:
            Type: Task
            Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}"
            Next: ConfigureTransform
          ConfigureTransform:
            Type: Pass
            Next: Transform
          Transform:
            Type: Task
            Resource: "arn:aws:lambda:us-east-1:795725798797:function:lambda-transform"
            ResultPath: $.transform
            Next: CheckResults  
          CheckResults: 
            Type: Choice
            Choices: 
              - Variable: "$.transform.extract.results['finished']"
                BooleanEquals: false
                Next: "Extract"
              - Variable: "$.transform.extract.results['finished']"
                BooleanEquals: true
                Next: "Finish"
          Finish:
            Type: "Succeed"  
plugins:
  - serverless-webpack
  - serverless-step-functions
  - serverless-pseudo-parameters

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true  

